### ISSUE TITLE
 Link Looks Malicious!

### ISSUE THREAD

**Issue by raghu-007** [cloudcommunity/Free-Certifications#109]
http://thetechco.in/MicrosoftAIforStudents/index

**Comment by Yajus114** [comment]
It doesn't seem to work, although a VirusTotal scan reveals nothing malicious
![image](https://github.com/cloudcommunity/Free-Certifications/assets/68367873/0bb3bf2d-5702-479b-b8be-686675a3e16c)
Seems like a cheeky redirect to a sponsored website

**Comment by raghu-007** [comment]
![Screenshot 2023-09-09 010854](https://github.com/cloudcommunity/Free-Certifications/assets/50697306/23e6c36e-3c31-48be-985c-49ac1c74650a)
My AV(Kaspersky) Detected Link is malicious, Seems to be Weird and cheeky😀

**Comment by Yajus114** [comment]
Best to remove it then.
