### ISSUE TITLE
Couchbase Certification 

### ISSUE THREAD

**Issue by mayuri2307** [cloudcommunity/Free-Certifications#143]
Hi, you can also add Couchbase in the database section. It is a good growing DB which many companies have started to use. 
https://www.couchbase.com/academy/certification/

**Comment by karentamrazyan** [comment]
Their certification exams are not free, right? We list here only free certifications.

**Comment by mayuri2307** [comment]
> Their certification exams are not free, right? We list here only free certifications.

Oh I missed that. Thanks!

**Comment by Vinodgupta3** [comment]
Hi, Can you please help if we can have any Data Science related course for non technical background candidate
