### ISSUE TITLE
Free  Certificate

### ISSUE THREAD

**Issue by arixnetwork** [cloudcommunity/Free-Certifications#184]

**Comment by chromer030** [comment]
?

**Comment by millette** [comment]
<https://cloudstudy.net/>

> This site can’t provide a secure connectioncloudstudy.net sent an invalid response.
> ERR_SSL_PROTOCOL_ERROR

**Comment by CloudStudyNet** [comment]
thanks @millette . The site seem to be working properly now. Closing the issue.
