### ISSUE TITLE
Rancher Kubernetes course has wrong expiry date

### ISSUE THREAD

**Issue by CHISOM96** [cloudcommunity/Free-Certifications#19]
The course expires on July 14, 2021 not January 14, 2021.
![rancher](https://user-images.githubusercontent.com/29149442/106713527-df72bc80-65fa-11eb-83cc-e4e94c2f888d.PNG)

**Comment by karentamrazyan** [comment]
thanks a lot!!! Merged!

**Comment by CHISOM96** [comment]
> thanks a lot!!! Merged!

You are welcome
