### ISSUE TITLE
Certifications 

### ISSUE THREAD

**Issue by cdip03** [cloudcommunity/Free-Certifications#242]

**Comment by Moyoens** [comment]
منکه کیج شدم.چرا تون هایی که باید بیاد به حساب تونکیپرم میره جای دیگه.توی توویور ادرس جتون من را دیدم ولی نمیتونم ترانسفر انجام بدم.اددس حساب رو پیدا میکنم ولی نمیدونم برای کدوم اپلیکیشن هست.تمام دارایی من دارد از دستم میرود لطفا کمکم کنید
