### ISSUE TITLE
ArangoDB Certified Professional

### ISSUE THREAD

**Issue by ediazhu** [cloudcommunity/Free-Certifications#83]
https://www.arangodb.com/learn/certification/

> he exam has a time limit of 60 minutes. You need to achieve at least a score of 80% to pass, but you can retake the exam if you need to. When passing the exam successfully, you will receive a personal certificate to download and show your skills on Twitter, LinkedIn wherever you want.

**Comment by karentamrazyan** [comment]
great, can you (or anyone else) please submit a pull request with this certification?

**Comment by HarryVasanth** [comment]
> great, can you (or anyone else) please submit a pull request with this certification?

I've opened the PR for this:
- #241 

Thank you!
