### ISSUE TITLE
Application error in Invite Link 

### ISSUE THREAD

**Issue by sidharthviz** [cloudcommunity/Free-Certifications#84]

**Comment by karentamrazyan** [comment]
yes, Heroku has unfortunately discontinued their free tier that we used to host our auto-invite script. Someone needs to adapt the script https://github.com/thundergolfer/automated-github-organization-invites to support other free hosting platforms, like e.g. Render.com or fly.io.

**Comment by CloudStudyNet** [comment]
@sidharthviz you have just been invited to the org. Also, we have a new auto-invite script at https://cloudstudy.net/invite2github
